### ISSUE TITLE
Impossible to invoke Insert emoticon dialog after inserting emoticon in recent next snapshots

### ISSUE THREAD

**Issue by lukaszgo1** [nvdaes/emoticons#11]
## STR
1. install latest next snapshot of NVDA
2. Open notepad
3. Invoke insert emoticon dialog with NVDA+i and insert one of the emoticons.
4. Try to invoke dialog again.
## expected behavior
Dialog should open.
## Actual behavior
the following is written in the log
ERROR - unhandled exception (21:37:53.473):
Traceback (most recent call last):
  File "wx\core.pyc", line 3190, in <lambda>
  File "C:\Users\Lukasz\AppData\Roaming\nvda\addons\emoticons\globalPlugins\emoticons\__init__.py", line 137, in onInsertEmoticonDialog
  File "gui\__init__.pyc", line 186, in _popupSettingsDialog
RuntimeError: wrapped C/C++ object of type InsertEmoticonDialog has been deleted
## environment
Installed NVDA version next-15391,7335adb4 with Emoticons version 7.0.

**Comment by nvdaes** [comment]
Thanks for reporting this. 
Since Next snapshots include features which may or not be included in future versions of NVDA, I ensure add-ons are compatible with master snapshots. I will take attention on this when the mentioned snapshot is merged in master branch. 
Anyway, if you think there is any reason for fixing this before, please let us know. 

Kind regards

**Comment by k-kolev1985** [comment]
Hello,

Yes, I can also reproduce this. The log information seams to be the same, but I'll post it anyway:

ERROR - unhandled exception (18:47:49.405):
Traceback (most recent call last):
  File "wx\core.pyc", line 3190, in <lambda>
  File "C:\Users\kkole\AppData\Roaming\nvda\addons\emoticons\globalPlugins\emoticons\__init__.py", line 137, in onInsertEmoticonDialog
  File "gui\__init__.pyc", line 186, in _popupSettingsDialog
RuntimeError: wrapped C/C++ object of type InsertEmoticonDialog has been deleted

I can post the whole log file with log level set to "Debug", if necessary.

**Comment by nvdaes** [comment]
Hello, thanks @lukaszgo1 and @k-kolev1985 for your comments.
Now, in Alpha snapshots, the Insert Emoticon dialog can be opened, so I'm going to close this issue, since changes aren't not required.
Anyway, when beta snapshots are updated with recent changes fixing possible issues with the new decorator for scripts and WX Py 4, code will be adapted for ease of review and maintenance, since the last version of Emoticons is not compatible with NVDA 2017.3, and therefore compatibility with older version of Windows won't be broken with changes.
As always, further comments are appreciated.

**Comment by lukaszgo1** [comment]
Hi @nvdaes  
The dialog can be opened, but it cannot be reopened. Can you please run the latest alfa snapshot, and perform the STR given in the initial comment.

**Comment by nvdaes** [comment]
lukaszgo1 commented 6 minutes ago 

> The dialog can be opened, but it cannot be reopened. Can you please run the latest alfa snapshot, and perform the STR given in the initial comment.

You are right. Sorry so much :)
Then I will work on this when WX Py 4 and decorator script issues are fixed in beta snapshots, to work on a more stable code.
Thanks a lot

**Comment by lukaszgo1** [comment]
Fixed for me in version 8.0-dev. Closing @nvdaes Thanks for fixing.
