### ISSUE TITLE
suggestion of new features

### ISSUE THREAD

**Issue by titet11** [nvdaes/emoticons#33]
hello: I wish there was a function to customize the emoticons to my liking. for example, there should be a function to move emoticons up and down the list, and another function so that one can choose which emoticon tab to start as default. that is to say. I would like the default tab to be the emoticons tab, but there will be others who want to use the standard emoticons tab.

I also wish that each smiley could be edited and smileys could be added manually.

As an extra function, I would like that when pressing insert more i it would position me in the list of emoticons, instead of positioning me in the filter section.
Another feature for the future that I would like is the ability to copy an emoticon without pressing enter, but simply by pressing ctrl plus c.

another similar function would be to paste several emoticons into a text automatically by pressing the shortcut shift plus enter inside the emoticon box.
Thus, both functions could be used at the same time, both copying an emoticon with the enter key, and pasting several emoticons with shift plus enter.

**Comment by nvdaes** [comment]
Hello, can you provide use cases to explain why the function to move up and down emoticons, if we have a filter, is needed?
I understand that every personal preference or choice is absolutely valid, but to prioritize my work I need to know if this is absolutely needed, considering that adding extra functions may make dialogs more complex.
About the position of the dialog when you open it, are not enough the shortcuts and the filter to select a type of emoticon
About editing, have you considered to add symbols in NVDA's menu, Preferences, Symbols and punctuation dialog, and then use the Insert symbol dialog provided by this add-on, in tools submenu?
About saving the default radio button, if someone needs it we can discuss this feature. Shortcut keys are added in the dialog to select the different options.
I'll try to work in adding buttons to copy and add emoticons to the clipboard, not with control+c, that is managed by Windows and can be assigned to clipContentsDesigner add-on, but with dialog buttons.
Thanks.

cc: @Christianlm

**Comment by titet11** [comment]
@nvdaes 
1. By moving the emoticons, the user can more quickly search the emoticons they use most often, which is very necessary.

2. I'm aware of the shortcuts the plugin has, but if there was a function to start on a specific element, it might help so that the positioning doesn't change when exiting the dialog.
an example would be the following:

I'll press insert i:
By default, I have the full list of emoticons.
however, I will select an emoticon from the list called standard.

So once I've selected it, I'll press insert plus i again.
When I press insert plus i again, I'm no longer in the list of all smileys, but now I'm in the standard list of smileys I don't like.
So the whole point of this is that there is the ability to choose which emoticon list I want to be the default.
3. Please note that you cannot mix a symbol list with an emoji list for the following reasons:
1. The nvda symbol list contains over 4000 symbols, and searching for an emoticon in the same list will waste a lot of time. Also, nvda's symbol list cannot move items up and down either.


 Also, it's not the same to insert an added emoticon into a symbols list, it's a waste of time to keep pressing insert more nvda and then go to the symbols section.
That is why it would be very useful if this plugin had the possibility to add, edit and delete each of its emoticons.
There will always be new smileys to add, so this feature would be very useful.
4. Something very useful would be to paste the emoticons automatically without closing the dialog by pressing shift plus enter.

**Comment by nvdaes** [comment]
Please, test this new version to see if this is enough. It adds the
ability to associate gestures to type symbols without copying them,
just type. You have to go to the input gestures dialog, Insert Symbols
category, use the Filter by edit box and search for a symbol like kiss
or whatever.You can add or remove gestures.
For now I think this is enough, but of course I'm open to add new
features if people explores the existent capabilities and provide use
cases.

https://github.com/nvdaes/emoticons/releases/download/16.2.0/emoticons-16.2.0.nvda-addon

2023-03-16 22:06 GMT+01:00, titet11 ***@***.***>:

**Comment by titet11** [comment]
Hello. I hope you have read the comment I left you before.

As for the new feature, it's still insufficient and a waste of time because as I said before, the ability to add, edit, and delete emoticons should be in the same dialog when you press insert plus i.
don't forget to add all the suggestions I mentioned above, they are quite useful, mainly the one to order the emoticons.

As an extra tip, you should export all emoticons that NVDA included in its default symbol list and add them to your plugin.

**Comment by nvdaes** [comment]
Hello:

The emoticons included in NVDA are available from the emoticons add-on
via the Insert symbol dialog. The Insert emoticon dialog is a legacy
dialog which maybe useful, but the Insert symbol dialog adds the
ability to copy symbols available in NVDA. This dialog doesn't have a
keystroke by default, but you may want to use Insert+i to open it
instead of the legacy Insert emoticon.
For now I think that I won't add the order emoticons function since
the Symbols dialog of NVDA doesn't have it and the filter edit box
seems to be enough. You may open an issue in NVDA's core. If this is
added in NVDA, automatically it will be added in this add-on since it
uses a subclass of the NVDA symbols dialog.
Please explore it and feel free to request other features.

2023-03-16 23:05 GMT+01:00, titet11 ***@***.***>:

**Comment by titet11** [comment]
@nvdaes 
Just because NVDA hasn't yet added the functionality to sort emoticons doesn't mean it's unnecessary or useless.

In addition, each user has different preferences, so having an order in the smileys will allow users to find the smileys they usually use with less difficulty.
Note that searching for a smiley by its specific name is not the same as searching for it in a list of smileys that have a defined order. therefore, searching for an emoticon by the specified name may take longer than searching a list in a specific order.

**Comment by nvdaes** [comment]
I may add a button to open a dialog inside the insert symbol dialog,  to type the desired position for the selected symbol; anyway this won"t be prioritized since the filter edit box can be used; when I have time i may do it.Enviado desde mi iPhoneEl 24 mar 2023, a las 1:39, titet11 ***@***.***> escribió:﻿
@nvdaes
Just because NVDA hasn't yet added the functionality to sort emoticons doesn't mean it's unnecessary or useless.
In addition, each user has different preferences, so having an order in the smileys will allow users to find the smileys they usually use with less difficulty.
Note that searching for a smiley by its specific name is not the same as searching for it in a list of smileys that have a defined order. therefore, searching for an emoticon by the specified name may take longer than searching a list in a specific order.
